# Generated by Django 3.2.5 on 2021-07-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_title', models.CharField(max_length=50)),
                ('comment_dsc', models.CharField(max_length=350)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.info')),
            ],
        ),
    ]
