# Generated by Django 3.2.5 on 2021-08-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_alter_info_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='commenter_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
