# Generated by Django 3.2.5 on 2021-08-09 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20210809_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='send_date',
            field=models.DateField(default=datetime.date(2021, 8, 9)),
        ),
    ]
