# Generated by Django 3.2.5 on 2021-08-09 21:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_comment_send_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 9, 21, 41, 32, 408845, tzinfo=utc)),
        ),
    ]
