# Generated by Django 3.2.5 on 2021-08-10 09:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_alter_comment_send_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='send_date',
            field=models.DateField(default=datetime.datetime(2021, 8, 10, 9, 23, 59, 45296, tzinfo=utc)),
        ),
    ]
